### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bkmagnetron** [sshivaji/kivy-chess#1]
```
[INFO   ] Kivy v1.8.0-dev
[INFO   ] [Logger      ] Record log in /home/bk/.kivy/logs/kivy_13-11-10_64.txt
[INFO   ] [Factory     ] 155 symbols loaded
[DEBUG  ] [Cache       ] register <kv.image> with limit=None, timeout=60s
[DEBUG  ] [Cache       ] register <kv.atlas> with limit=None, timeout=Nones
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_pygame, img_pil, img_gif 
[DEBUG  ] [Cache       ] register <kv.texture> with limit=1000, timeout=60s
[DEBUG  ] [Cache       ] register <kv.shader> with limit=1000, timeout=3600s
[DEBUG  ] [Cache       ] register <kv.lang> with limit=None, timeout=Nones
[INFO   ] [Text        ] Provider: pygame
[DEBUG  ] [Window      ] Ignored <egl_rpi> (import error)
[INFO   ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
[DEBUG  ] [Window      ] Display driver x11
[DEBUG  ] [Window      ] Actual window size: 1025x768
[DEBUG  ] [Window      ] Actual color bits r8 g8 b8 a0
[DEBUG  ] [Window      ] Actual depth bits: 24
[DEBUG  ] [Window      ] Actual stencil bits: 8
[DEBUG  ] [Window      ] Actual multisampling samples: 2
[INFO   ] [GL          ] OpenGL version <3.0 Mesa 9.2.1>
[INFO   ] [GL          ] OpenGL vendor <nouveau>
[INFO   ] [GL          ] OpenGL renderer <Gallium 0.4 on NV96>
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <1.30>
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <16>
[DEBUG  ] [Shader      ] Fragment compiled successfully
[DEBUG  ] [Shader      ] Vertex compiled successfully
[DEBUG  ] [ImagePygame ] Load </usr/lib/python2.7/dist-packages/kivy/data/glsl/default.png>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[DEBUG  ] [Cache       ] register <kv.loader> with limit=500, timeout=60s
[INFO   ] [Loader      ] using a thread pool of 2 workers
[DEBUG  ] [Cache       ] register <textinput.label> with limit=None, timeout=60.0s
[DEBUG  ] [Cache       ] register <textinput.width> with limit=None, timeout=60.0s
 Traceback (most recent call last):
   File "main.py", line 51, in <module>
     from chess import polyglot_opening_book
   File "/home/bk/Desktop/kivy-chess-master/chess/__init__.py", line 30, in <module>
     from libchess import START_FEN
 ImportError: /home/bk/Desktop/kivy-chess-master/chess/libchess.so: invalid ELF header
```

**Comment by balakrishnangithub** [comment]
took a long time
