### ISSUE TITLE
libchess module missing on Mac OS X

### ISSUE THREAD

**Issue by nallapan** [sshivaji/kivy-chess#5]
Hi, I am seeing this error on the Mac OSX. Followed all the steps. Am I missing some steps?

(chess)kivy-chess$ kivy main.py
[INFO              ] Kivy v1.8.0
Purge log fired. Analysing...
Purge finished !
[INFO              ] [Logger      ] Record log in /Users/sainalla/.kivy/logs/kivy_14-10-08_14.txt
[INFO              ] [Factory     ] 157 symbols loaded
[DEBUG             ] [Cache       ] register <kv.image> with limit=None, timeout=60s
[DEBUG             ] [Cache       ] register <kv.atlas> with limit=None, timeout=Nones
[INFO              ] [Image       ] Providers: img_imageio, img_tex, img_dds, img_pygame, img_gif (img_pil ignored)
[DEBUG             ] [Cache       ] register <kv.texture> with limit=1000, timeout=60s
[DEBUG             ] [Cache       ] register <kv.shader> with limit=1000, timeout=3600s
[DEBUG             ] [Cache       ] register <kv.lang> with limit=None, timeout=Nones
[INFO              ] [Text        ] Provider: pygame
[DEBUG             ] [Window      ] Ignored <egl_rpi> (import error)
[INFO              ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
[DEBUG             ] [Window      ] Display driver Quartz
[DEBUG             ] [Window      ] Actual window size: 800x600
[DEBUG             ] [Window      ] Actual color bits r8 g8 b8 a8
[DEBUG             ] [Window      ] Actual depth bits: 24
[DEBUG             ] [Window      ] Actual stencil bits: 8
[DEBUG             ] [Window      ] Actual multisampling samples: 2
[INFO              ] [GL          ] OpenGL version <2.1 NVIDIA-8.26.28 310.40.55b01>
[INFO              ] [GL          ] OpenGL vendor <NVIDIA Corporation>
[INFO              ] [GL          ] OpenGL renderer <NVIDIA GeForce GT 650M OpenGL Engine>
[INFO              ] [GL          ] OpenGL parsed version: 2, 1
[INFO              ] [GL          ] Shading version <1.20>
[INFO              ] [GL          ] Texture max size <16384>
[INFO              ] [GL          ] Texture max units <16>
[DEBUG             ] [Shader      ] Fragment compiled successfully
[DEBUG             ] [Shader      ] Vertex compiled successfully
[DEBUG             ] [ImageImageIO] Load </Applications/Kivy.app/Contents/Resources/kivy/kivy/data/glsl/default.png>
[INFO              ] [GL          ] BGRA texture support is available
[INFO              ] [Window      ] virtual keyboard not allowed, single mode, not docked
[DEBUG             ] [Cache       ] register <kv.loader> with limit=500, timeout=60s
[INFO              ] [Loader      ] using a thread pool of 2 workers
[DEBUG             ] [Cache       ] register <textinput.label> with limit=None, timeout=60.0s
[DEBUG             ] [Cache       ] register <textinput.width> with limit=None, timeout=60.0s
 Traceback (most recent call last):
   File "main.py", line 61, in <module>
     from chess import polyglot_opening_book
   File "/Users/sainalla/Projects/chess/kivy-chess/chess/**init**.py", line 30, in <module>
     from libchess import START_FEN
 ImportError: No module named libchess

**Comment by Spill-The-Tea** [comment]
I've been struggling to install Kivy-Chess on my mac.
I downloaded the libchess branch of Kivychess, and I've managed to overcome a number of obstacles, including figuring out how to compile libchess.so library, but still cannot manage to run the program. After ./run.sh, i recieve the following response:

 Traceback (most recent call last):
   File "main.py", line 99, in <module>
     from chess import libchess
   File "/Users/SpillTheTea/Documents/JDel Rio/Chess Games/Chess GUIs/kivy-chess-libchess/chess/__init__.py", line 30, in <module>
     from libchess import START_FEN
   File "build/bdist.macosx-10.14-x86_64/egg/libchess.py", line 7, in <module>
   File "build/bdist.macosx-10.14-x86_64/egg/libchess.py", line 6, in __bootstrap__
 ImportError: dlopen(/Users/SpillTheTea/Library/Caches/Python-Eggs/python_chess-0.0.5-py2.7-macosx-10.14-x86_64.egg-tmp/libchess.so, 2): Symbol not found: __ZN5boost6python17error_already_setD1Ev
   Referenced from: /Users/SpillTheTea/Library/Caches/Python-Eggs/python_chess-0.0.5-py2.7-macosx-10.14-x86_64.egg-tmp/libchess.so
   Expected in: flat namespace
  in /Users/SpillTheTea/Library/Caches/Python-Eggs/python_chess-0.0.5-py2.7-macosx-10.14-x86_64.egg-tmp/libchess.so



Which makes me think, that I may have compiled the libchess.so library wrong. I needed to change the setup.py file from python-chess, needed to link both the boost-regex and boost-python libraries, to directly point to the directory on my computer. Here are the libraries I specifically used:
                "/usr/local/Cellar/boost-python/1.68.0/lib/**libboost_python27.dylib**",
                "/usr/local/Cellar/boost/1.68.0/lib/**libboost_regex.dylib**",
